# Generated by Django 3.0.6 on 2020-09-29 12:50

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bridge', '0002_auto_20200929_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
